from __future__ import annotations

from typing import Any

import numpy as np

from .utils import require_finite


def run_ray_bundle(cfg: dict[str, Any]) -> dict[str, Any]:
    """Propagate a two-dimensional Jacobi map through frozen linearized screens.

    The screen recurrence is an implementation engine only. The physical metric,
    screen tensors, and distance weights must be generated by the RFC K/N lineage.
    """
    screens = require_finite("screen_tensors", cfg["screen_tensors"])
    weights = require_finite("distance_weights", cfg["distance_weights"])
    if screens.ndim != 3 or screens.shape[1:] != (2, 2) or weights.shape != (screens.shape[0],):
        raise ValueError("screen_tensors must be count x 2 x 2 with one distance weight each")
    jacobi = np.asarray(cfg.get("initial_jacobi", np.eye(2)), dtype=float)
    if jacobi.shape != (2, 2):
        raise ValueError("initial_jacobi must be 2x2")
    history = [jacobi.copy()]
    for screen, weight in zip(screens, weights):
        jacobi = (np.eye(2) - float(weight) * screen) @ jacobi
        history.append(jacobi.copy())
    determinant = float(np.linalg.det(jacobi))
    trace = float(np.trace(jacobi))
    antisymmetric_error = float(abs(jacobi[0, 1] - jacobi[1, 0]))
    convergence = float(1.0 - trace / 2.0)
    shear_1 = float((jacobi[1, 1] - jacobi[0, 0]) / 2.0)
    shear_2 = float(-(jacobi[0, 1] + jacobi[1, 0]) / 2.0)
    tolerance = float(cfg.get("finite_tolerance", 1e-12))
    pass_flags = {
        "finite": bool(np.all(np.isfinite(jacobi))),
        "non_singular": abs(determinant) > tolerance,
    }
    return {
        "success": bool(all(pass_flags.values())),
        "classification": "LINEARIZED_RAY_JACOBI_PROPAGATION",
        "jacobi_history": [x.tolist() for x in history],
        "final_jacobi": jacobi.tolist(),
        "determinant": determinant,
        "magnification": float(1.0 / determinant),
        "convergence": convergence,
        "shear": [shear_1, shear_2],
        "rotation_indicator": antisymmetric_error,
        "pass_flags": pass_flags,
    }
